# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_full <- function(n_iter, n_save, Z, theta_t, ind_zero, mu_t, p_t, h_t, psi_t, ind_mat, lambda0_t, lambda1_t, C_t, R_t, sgm_sq_t, sgm_sq_star_t, gam_1, gam_2, G, n, m, K, S, sgm_sq_vare_t, eta_mu = 0, tau_mu = 5, alpha_1 = 2, beta_1 = 0.1, gamma_0 = 1000.0, alpha_vare = 3, beta_vare = 0.1, alpha_2 = 5, beta_2 = 0.01, tau_0 = 0.1, eta_psi = 0, tau_psi = 10, epsilon_theta = 0.2, num_step_theta = 20L, lam0_0 = 2, lam1_0 = -2, sigma2_lam0 = 0.25, sigma2_lam1 = 0.25, epsilon_lam = 0.01, num_step_lam = 10L, iter_save = FALSE, iter_print = 1000L, class_print = FALSE) {
    .Call(`_BayesEATS_MCMC_full`, n_iter, n_save, Z, theta_t, ind_zero, mu_t, p_t, h_t, psi_t, ind_mat, lambda0_t, lambda1_t, C_t, R_t, sgm_sq_t, sgm_sq_star_t, gam_1, gam_2, G, n, m, K, S, sgm_sq_vare_t, eta_mu, tau_mu, alpha_1, beta_1, gamma_0, alpha_vare, beta_vare, alpha_2, beta_2, tau_0, eta_psi, tau_psi, epsilon_theta, num_step_theta, lam0_0, lam1_0, sigma2_lam0, sigma2_lam1, epsilon_lam, num_step_lam, iter_save, iter_print, class_print)
}

